name: final

services:
  frontend:
    build:
      context: ./frontend
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  backend:
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file: .env
    build:
      context: ./backend

  api-1:
    ports:
      - "${API1_PORT}:${API1_PORT}"
    env_file: .env
    build:
      context: ./api-1

  api-2:
    ports:
      - "${API2_PORT}:${API2_PORT}"
    env_file: .env
    build:
      context: ./api-2
