name: midterm

services:
  frontend:
    build:
      context: ./frontend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5173:5173"
  backend:
    ports:
      - "8800:8800"
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
  database:
    build: .
    command: --init-file /db/books.sql
    environment:
      - MYSQL_ROOT_PASSWORD=test
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "--password=test", "status"]
      interval: 5s
      timeout: 5s
      retries: 2
      start_period: 5s
